export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: '墨圆大模型',
      description: '从大模型基础到企业级 AI 应用落地的系统学习平台。',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: true,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.75,
    },
    banner: {
      enable: false,
      showClose: true,
      content: 'Welcome to **shadcn-docs-nuxt**',
      to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
      target: '_blank',
      border: true,
    },
    header: {
      title: '墨圆大模型',
      showTitle: true,
      logo: {
        light: '/logo-light.svg',
        dark: '/logo-dark.svg',
      },
      border: false,
      darkModeToggle: true,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: '学习路线',
        links: [{
          title: '零基础入门',
          to: '/learning-path/zero-basics',
          description: '从认知和术语开始，先建立大模型学习框架。',
          icon: 'lucide:sparkles',
        }, {
          title: '开发者转大模型',
          to: '/learning-path/dev-transition',
          description: '用工程视角补齐模型能力，快速完成能力迁移。',
          icon: 'lucide:git-branch',
        }, {
          title: '面试速成',
          to: '/learning-path/interview-accelerator',
          description: '聚焦高频考点与表达结构，提升面试通过率。',
          icon: 'lucide:target',
        }, {
          title: '企业应用路线',
          to: '/learning-path/enterprise-route',
          description: '从 PoC 到生产落地，掌握企业级应用关键环节。',
          icon: 'lucide:building-2',
        }],
      }, {
        title: '核心专题',
        links: [{
          title: '大模型基础',
          to: '/components/transformer',
          description: '模型原理、Token 与常见模型体系。',
          icon: 'lucide:brain-circuit',
        }, {
          title: 'Prompt 工程',
          to: '/api/prompt-basics',
          description: 'Prompt 设计、优化与上下文策略。',
          icon: 'lucide:message-square-text',
        }, {
          title: 'Agent',
          to: '/agent/what-is-agent',
          description: '工具调用、记忆设计与多 Agent 协同。',
          icon: 'lucide:bot',
        }, {
          title: 'RAG',
          to: '/rag/rag-principles',
          description: '检索增强生成与企业知识库落地。',
          icon: 'lucide:database',
        }, {
          title: 'MCP / Tool Calling',
          to: '/topics',
          description: '模型调用工具的通用协议与实践方式。',
          icon: 'lucide:plug',
        }, {
          title: '推理与部署',
          to: '/ai-practice/backend-service',
          description: '服务封装、并发控制与生产部署要点。',
          icon: 'lucide:server',
        }, {
          title: '评测与优化',
          to: '/ai-practice/logging-monitoring',
          description: '可观测性、效果评估与性能优化。',
          icon: 'lucide:gauge',
        }, {
          title: '多模态',
          to: '/topics',
          description: '文本、图像、语音等多模态应用路线。',
          icon: 'lucide:images',
        }],
      }, {
        title: '项目实战',
        links: [{
          title: 'Chat 应用',
          to: '/projects/chatgpt-clone',
          description: '构建具备上下文管理的对话应用。',
          icon: 'lucide:messages-square',
        }, {
          title: 'RAG 知识库',
          to: '/projects/doc-qa-system',
          description: '从文档解析到问答链路的完整实现。',
          icon: 'lucide:book-open-text',
        }, {
          title: 'Agent 工作流',
          to: '/projects/agent-platform',
          description: '规划、执行、工具调用的工作流编排。',
          icon: 'lucide:workflow',
        }, {
          title: '企业级 AI 应用',
          to: '/projects/ai-cs-system',
          description: '面向业务场景的智能客服系统设计。',
          icon: 'lucide:building',
        }],
      }, {
        title: '面试题',
        links: [{
          title: '高频术语',
          to: '/interview-resources/glossary',
          description: '面试中最常见概念的速查索引。',
          icon: 'lucide:book-type',
        }, {
          title: '常见问题',
          to: '/interview-resources/faq',
          description: '学习与求职阶段高频问题总结。',
          icon: 'lucide:circle-help',
        }, {
          title: '学习路线图',
          to: '/interview-resources/roadmap',
          description: '按阶段安排学习内容与里程碑。',
          icon: 'lucide:map',
        }, {
          title: '面试题整理',
          to: '/interview-resources/questions',
          description: '按专题整理可复盘的面试问题。',
          icon: 'lucide:list-checks',
        }, {
          title: '资源推荐',
          to: '/interview-resources/recommendations',
          description: '高质量资料与工具清单推荐。',
          icon: 'lucide:library',
        }],
      }, {
        title: '博客 / 更新',
        links: [{
          title: '新文章',
          to: '/blog',
          description: '最新文章与实践总结。',
          icon: 'lucide:newspaper',
        }, {
          title: '版本更新',
          to: '/blog/v1-1',
          description: '版本记录与功能变化说明。',
          icon: 'lucide:history',
        }, {
          title: '行业观察',
          to: '/blog',
          description: '行业趋势与应用案例观察。',
          icon: 'lucide:binoculars',
        }, {
          title: '踩坑记录',
          to: '/blog',
          description: '真实项目中的问题与规避方案。',
          icon: 'lucide:triangle-alert',
        }],
      }, {
        title: '关于 / 致谢',
        links: [{
          title: '关于墨圆',
          to: '/about/project',
          description: '项目愿景、定位与内容规划。',
          icon: 'lucide:circle-user-round',
        }, {
          title: '开源鸣谢',
          to: '/about/acknowledgements',
          description: '感谢所有开源项目与社区贡献。',
          icon: 'lucide:heart-handshake',
        }, {
          title: '联系方式',
          to: '/about/contact',
          description: '合作咨询与内容共建联系入口。',
          icon: 'lucide:mail',
        }, {
          title: '友情链接',
          to: '/about/friends',
          description: '推荐站点与学习资源导航。',
          icon: 'lucide:link',
        }],
      }],
      links: [
        {
          icon: 'lucide:github',
          to: 'https://github.com/AoHanBei/moyuanAI-front',
          target: '_blank',
        },
      ],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: false,
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      border: true,
      credits: '',
      links: [],
    },
    toc: {
      enable: true,
      enableInMobile: true,
      enableInHomepage: false,
      progressBar: true,
      title: 'On this page',
      links: [
        {
          title: '查看 GitHub 仓库',
          icon: 'lucide:star',
          to: 'https://github.com/AoHanBei/moyuanAI-front',
          target: '_blank',
          showLinkIcon: true,
        },
        {
          title: '提交反馈 / Issues',
          icon: 'lucide:circle-dot',
          to: 'https://github.com/AoHanBei/moyuanAI-front/issues',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        {
          icon: 'lucide:github',
          to: 'https://github.com/AoHanBei/moyuanAI-front',
          target: '_blank',
        },
      ],
      carbonAds: {
        enable: true,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});
