export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: '墨圆大模型',
      description: '从大模型基础到企业级 AI 应用落地的系统学习平台。',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: true,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: true,
      color: 'blue',
      radius: 0.75,
    },
    banner: {
      enable: false,
      showClose: true,
      content: '',
      to: '',
      target: '_blank',
      border: true,
    },
    header: {
      title: '墨圆大模型',
      showTitle: true,
      logo: {
        light: '/logo-light.svg',
        dark: '/logo-dark.svg',
      },
      border: false,
      darkModeToggle: true,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [
        {
          title: '学习路线',
          to: '/learning-path',
          showLinkIcon: false,
        },
        {
          title: '核心专题',
          to: '/topics',
          showLinkIcon: false,
        },
        {
          title: '项目实战',
          to: '/projects',
          showLinkIcon: false,
        },
        {
          title: '面试与资料',
          to: '/interview-resources',
          showLinkIcon: false,
        },
        {
          title: '关于 / 联系',
          to: '/about/acknowledgements',
          showLinkIcon: false,
        },
      ],
      links: [
        {
          icon: 'lucide:github',
          to: 'https://github.com/AoHanBei/moyuanAI-front',
          target: '_blank',
        },
      ],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: true,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: false,
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
      },
    },
    footer: {
      border: false,
      credits: '',
      links: [],
    },
    toc: {
      enable: true,
      enableInMobile: true,
      enableInHomepage: false,
      title: '本页目录',
      links: [],
      iconLinks: [],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: true,
        code: '',
        placement: '',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
  },
});
